#!/bin/bash

# Monitors layout
#$HOME/.config/xrandr/launch.sh &

sxhkd &

# Config

bspc monitor HDMI-1 -d			1 2 3 4 5
#bspc monitor DP-1 -d			6 7 8 9 0

#bspc config active_border_color	"#282A2E"
#bspc config focused_border_color	"#C5C8C6"
bspc config presel_feedback_color	"#F0C674"

bspc config border_width		0
bspc config window_gap			0

bspc config split_ratio			0.5

bspc config focus_follows_pointer	true
#bspc config pointer_follows_focus	true

#bspc config borderless_monocle		true
#bspc config gapless_monocle		true

# Wallpapers
$HOME/.config/feh/launch.sh &

# Polybar
$HOME/.config/polybar/launch.sh &
