#!/bin/bash

sxhkd &

xset s 120 30
xss-lock -n /usr/libexec/xsecurelock/dimmer -l -- xsecurelock &

# Config

bspc monitor -d				1 2 3 4 5 6

bspc config presel_feedback_color	"#F0C674"

bspc config border_width		0
bspc config window_gap			0

bspc config split_ratio			0.5

bspc config focus_follows_pointer	true
#bspc config borderless_monocle		true
#bspc config gapless_monocle		true

# Bar
polybar &
